### ISSUE TITLE
Blog Post: How to mine BALN

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/docs#1]
Write a guide on how to:

- Mine BALN on Homepage
- Mine BALN on DEX
- Claim BALN
- Stake BALN

**Comment by parrot9design** [comment]
Draft: https://docs.google.com/document/d/1yqD_GhG5nqiEcYUhKOIEMLPojxmD11J3-pEd8cHcbGw/edit?usp=sharing

**Comment by parrot9design** [comment]
Final post: https://balanceddao.medium.com/how-to-earn-balance-tokens-6aafb7d6dd5
