### ISSUE TITLE
Blog Post: What is sICX and how does it work?

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/docs#2]
Cover the following topics:

- The number of sICX you hold will not increase, but the number of ICX in the staking pool will increase, that's how staking rewards are recognized
- You can trade ICX for sICX for free on the DEX
- When you deposit into Balanced collateral, your ICX is converted to sICX automatically
- When you withdraw, you will receive sICX
- Explain the sICX / ICX pool and how to instantly convert your sICX back to ICX

**Comment by parrot9design** [comment]
Draft is here: https://docs.google.com/document/d/1Ccr2ahTPOhjucwzkGd8T4W85hvt-QfEMlFWITVh7VGA/edit#heading=h.88wj2dfo1ijh

**Comment by parrot9design** [comment]
Final post: https://balanceddao.medium.com/what-is-sicx-and-how-does-it-work-238e09f59c06
