### ISSUE TITLE
Add to docs.balanced.network - How APY is calculated

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/docs#7]

**Comment by parrot9design** [comment]
Liquidity: https://docs.balanced.network/user-guide/supply-liquidity
<img width="710" alt="Screen Shot 2021-04-29 at 1 09 00 PM" src="https://user-images.githubusercontent.com/63842577/116490759-43500d00-a8ec-11eb-9846-bf29651d4e1d.png">

Loan : https://docs.balanced.network/user-guide/manage-position
<img width="686" alt="Screen Shot 2021-04-29 at 1 10 14 PM" src="https://user-images.githubusercontent.com/63842577/116490760-45b26700-a8ec-11eb-8709-9d0fca6375a7.png">
